package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author Gustavo
 */
public class AdminView extends javax.swing.JFrame {
    
    /**    
    /**
     * Creates new form MainView
     */
    public AdminView(){
        initComponents();
        this.setTitle("LGC - HermosoStovisk");
        decoracao();
        
        miCadastrarProduto.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				CadastroProdutoView cpv = new CadastroProdutoView();
				cpv.setVisible(true);
				
			}} );
        
        miCadastrarCategoria.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				CadastroCategoriaView ccv = new CadastroCategoriaView();
				ccv.setVisible(true);
				
			}} );
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBoasVindas = new javax.swing.JLabel();
        lbMensagem = new javax.swing.JLabel();
        lbMensagem1 = new javax.swing.JLabel();
        lbImg = new javax.swing.JLabel();
        mbMain = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        miCadastrarProduto = new javax.swing.JMenuItem();
        miCadastrarCategoria = new javax.swing.JMenuItem();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(63, 63, 70));

        lbBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBoasVindas.setForeground(new java.awt.Color(250, 250, 249));
        lbBoasVindas.setText("Olá,");

        lbMensagem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMensagem.setText("Bem-Vindo(a) Ao Hermozotovisk,");

        lbMensagem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMensagem1.setText("Seu Gerenciador de Estoque Favorito!");

        lbImg.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbImg.setIcon(new javax.swing.ImageIcon("images/logo.png")); // NOI18N
        lbImg.setText("Hermozotoviski");

        mCadastro.setText("Cadastrar");

        miCadastrarCategoria.setText("Cadastrar Categorias");
        mCadastro.add(miCadastrarCategoria);

        miCadastrarProduto.setText("Cadastrar Produtos");
        mCadastro.add(miCadastrarProduto);

       mbMain.add(mCadastro);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBoasVindas)
                    .addComponent(lbMensagem1)
                    .addComponent(lbMensagem)
                    .addComponent(lbImg))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbBoasVindas)
                .addGap(18, 18, 18)
                .addComponent(lbMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMensagem1)
                .addGap(32, 32, 32)
                .addComponent(lbImg)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBoasVindas;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JLabel lbMensagem1;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miCadastrarCategoria;
    private javax.swing.JMenuItem miCadastrarProduto;
    // End of variables declaration//GEN-END:variables

   
    private void decoracao(){
        getContentPane().setBackground(getBackground());
//        lbBoasVindas.setText("Olá " + adm.getNome() + ", Boa noite");
        lbBoasVindas.setForeground(Color.decode("#fafaf9"));
        mbMain.setBackground(Color.decode("#71717a"));
        mCadastro.setForeground(Color.decode("#fafaf9"));
        miCadastrarCategoria.setForeground(Color.decode("#fafaf9"));
        miCadastrarProduto.setForeground(Color.decode("#fafaf9"));
        miCadastrarCategoria.setBackground(Color.decode("#71717a"));
        miCadastrarProduto.setBackground(Color.decode("#71717a"));
        lbMensagem.setForeground(Color.decode("#fafaf9"));
        lbMensagem1.setForeground(Color.decode("#fafaf9"));
        lbImg.setForeground(Color.decode("#fafaf9"));
    }
}
