package view;

import controller.ControllerCadastroProduto;
import dao.CategoriaDAO;
import dao.ProdutoDAO;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

import model.Categoria;
import model.Produto;
import observer.ObserverCadastroProduto;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */

public class CadastroProdutoView extends javax.swing.JFrame implements ObserverCadastroProduto {

    class AdaptadorDeRato extends MouseAdapter {
        @Override
        public void mouseClicked(MouseEvent e) {
                JTable table = (JTable)e.getSource();
                int row = table.getSelectedRow();
                String descricaoProduto = table.getValueAt(row, 0).toString();
                controller.recuperarProduto(descricaoProduto);
            }
    }

    private ControllerCadastroProduto controller;
    public CadastroProdutoView() {
        this.controller = new ControllerCadastroProduto();
        this.controller.anexarObserver(this);

        initComponents();
        decoracao();
        this.setTitle("Cadastrar Produtos");

        this.controller.setUpInfo();

        tbListaProdutos.addMouseListener(new AdaptadorDeRato());

        btCadastro.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
                // validarCampos();
                controller.criarProduto(tfNomeProduto.getText(), getPrecoProduto(), tfDescricaoProduto.getText(), getCategoriaProduto());
                dispose();
			}});

    }
    public void exibirMensagem(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem);
    }

    @Override
    public void criandoProduto(String nome) {
//        exibirMensagem("Produto Criado com succeso! Nome: " + nome);
    }

    @Override
    public void listandoCategorias(List<Categoria> categorias) {
        for(Categoria cat: CategoriaDAO.categorias){
            cbCategoria.addItem(cat);
        }
    }

    public void getProdutoSelecionado(){
        DefaultTableModel model = (DefaultTableModel) tbListaProdutos.getModel();
        String p = (String) tbListaProdutos.getValueAt(tbListaProdutos.getSelectedRow(), tbListaProdutos.getSelectedColumn());
        tbListaProdutos.getValueAt(tbListaProdutos.getSelectedRow(), tbListaProdutos.getSelectedColumn());
//        p = (Produto) tbListaProdutos.getValueAt(tbListaProdutos.getSelectedRow(), tbListaProdutos.getSelectedColumn());
    }

    public Categoria getCategoriaProduto(){
        return (Categoria) cbCategoria.getSelectedItem();
    }
    
    public Double getPrecoProduto(){
        return Double.parseDouble(tfPrecoProduto.getText());
    }
    
     public int getQuantidadeProduto(){
        return Integer.parseInt(tfQuantidade.getText());
    }
 
     public void limpaCampos(){
        tfDescricaoProduto.setText("");
        tfNomeProduto.setText("");
        tfPrecoProduto.setText("");
        tfQuantidade.setText("");
    }
    @Override
    public void listandoProdutos(List<Produto> produtos) {

        DefaultTableModel model = (DefaultTableModel) tbListaProdutos.getModel();
        model.setRowCount(0);
        for (Produto p : produtos) {
            
            Object data[] = {
                p.getNome(), p.getCategoria(), p.getPreco(), p.getDescricao()
            };
            model.addRow(data);
        }
    }

    @Override
    public void recuperandoProduto(Produto produto) {
        tfDescricaoProduto.setText(produto.getDescricao());
        tfNomeProduto.setText(produto.getNome());
        tfPrecoProduto.setText(Double.toString(produto.getPreco()));
        tfQuantidade.setText(String.valueOf(produto.getQuantidade()));
        cbCategoria.setSelectedItem(produto.getCategoria());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfNomeProduto = new javax.swing.JTextField();
        tfPrecoProduto = new javax.swing.JTextField();
        lbTituloProduto = new javax.swing.JLabel();
        lbNomeProduto = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        lbNomeCategoria = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();
        lbDesc = new javax.swing.JLabel();
        btCadastro = new javax.swing.JButton();
        tfDescricaoProduto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListaProdutos = new javax.swing.JTable();
        lbListaProduto = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        lbQTD = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfPrecoProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbTituloProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTituloProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloProduto.setLabelFor(this);
        lbTituloProduto.setText("Cadastro de Produto");
        lbTituloProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNomeProduto.setText("Nome do Produto");

        lbNomeCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNomeCategoria.setText("Selecionar Categoria");

        lbPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPreco.setText("Preço R$");

        lbDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDesc.setText("Descrição do Produto");

        btCadastro.setText("Cadastrar");


        tfDescricaoProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tbListaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Categoria", "Preço R$", "Descrição"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        });
        jScrollPane2.setViewportView(tbListaProdutos);

        lbListaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbListaProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbListaProduto.setText("Lista de Produtos");
        lbListaProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tfQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbQTD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbQTD.setText("Quantidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbQTD, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbDesc)
                    .addComponent(tfDescricaoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(cbCategoria, 0, 371, Short.MAX_VALUE)
                    .addComponent(lbNomeCategoria)
                    .addComponent(tfNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(lbNomeProduto)
                    .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbListaProduto)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(450, 450, 450))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lbTituloProduto)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeProduto)
                    .addComponent(lbListaProduto))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(lbNomeCategoria)
                        .addGap(8, 8, 8)
                        .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPreco)
                            .addComponent(lbQTD))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(lbDesc)
                        .addGap(8, 8, 8)
                        .addComponent(tfDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void decoracao(){
        getContentPane().setBackground(Color.decode("#3f3f46"));
        btCadastro.setBackground(Color.decode("#38bdf8"));
        btCadastro.setForeground(Color.decode("#fafaf9"));
        lbPreco.setForeground(Color.decode("#fafaf9"));
        lbDesc.setForeground(Color.decode("#fafaf9"));
        lbListaProduto.setForeground(Color.decode("#fafaf9"));
        tfDescricaoProduto.setBackground(Color.decode("#f3f4f6"));
        tfNomeProduto.setBackground(Color.decode("#f3f4f6"));
        tfPrecoProduto.setBackground(Color.decode("#f3f4f6"));
        tfQuantidade.setBackground(Color.decode("#f3f4f6"));
        tfDescricaoProduto.setForeground(Color.decode("#18181b"));
        tfNomeProduto.setForeground(Color.decode("#18181b"));
        tfPrecoProduto.setForeground(Color.decode("#18181b"));
        tfQuantidade.setForeground(Color.decode("#18181b"));
        lbQTD.setForeground(Color.decode("#fafaf9"));
        lbTituloProduto.setForeground(Color.decode("#fafaf9"));
        lbNomeProduto.setForeground(Color.decode("#fafaf9"));
        lbNomeCategoria.setForeground(Color.decode("#fafaf9"));
        tbListaProdutos.setBackground(Color.decode("#f3f4f6"));
        tbListaProdutos.setForeground(Color.decode("#18181b"));
        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JComboBox<Categoria> cbCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbDesc;
    private javax.swing.JLabel lbListaProduto;
    private javax.swing.JLabel lbNomeCategoria;
    private javax.swing.JLabel lbNomeProduto;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQTD;
    private javax.swing.JLabel lbTituloProduto;
    private javax.swing.JTable tbListaProdutos;
    private javax.swing.JTextField tfDescricaoProduto;
    private javax.swing.JTextField tfNomeProduto;
    private javax.swing.JTextField tfPrecoProduto;
    private javax.swing.JTextField tfQuantidade;

    // End of variables declaration//GEN-END:variables
}
